package models

import (
	"encoding/json"
	"fmt"
)

type AssistantMessage struct {
	// An optional name for the participant. Provides the model information to differentiate between participants of
	// the same role.
	Name string
	// The contents of the assistant message. Required unless ToolCalls is specified.
	Content string
	// The tool calls generated by the model, such as function calls.
	ToolCalls []ToolCall
}

func (message AssistantMessage) Message() Message {
	return message
}

func (message AssistantMessage) MarshalJSON() ([]byte, error) {
	out := struct {
		Role      MessageRole `json:"role"`
		Name      string      `json:"name,omitempty"`
		Content   string      `json:"content,omitempty"`
		ToolCalls []ToolCall  `json:"tool_calls,omitempty"`
	}{
		Role:      MessageRoleAssistant,
		Name:      message.Name,
		Content:   message.Content,
		ToolCalls: message.ToolCalls,
	}

	return json.Marshal(out)
}

func (message *AssistantMessage) UnmarshalJSON(data []byte) error {
	messageData := struct {
		Name      string      `json:"name"`
		Content   string      `json:"content"`
		ToolCalls []ToolCall  `json:"tool_calls"`
		Role      MessageRole `json:"role"`
	}{}

	if err := json.Unmarshal(data, &messageData); err != nil {
		return fmt.Errorf("AssistantMessage.UnmarshalJSON: %w", err)
	}

	if messageData.Role != MessageRoleAssistant {
		return fmt.Errorf("AssistantMessage.UnmarshalJSON: invalid role %s", messageData.Role)
	}

	message.Name = messageData.Name
	message.Content = messageData.Content

	if messageData.ToolCalls != nil {
		message.ToolCalls = messageData.ToolCalls
	}

	return nil
}
