package models

type ToolCall struct {
	// The ID of the tool call.
	ID string `json:"id"`
	// The type of the tool. Currently, only ToolTypeFunction is supported.
	Type ToolType `json:"type,omitempty"`
	// The function that the model called.
	Function *ToolCallFunction `json:"function,omitempty"`
}

type ToolCallFunction struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not
	// always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the
	// arguments in your code before calling your function.
	Arguments string `json:"arguments,omitempty"`
	// The name of the function to call.
	Name string `json:"name,omitempty"`
}
