// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStreamWaitFn is an autogenerated mock type for the StreamWaitFn type
type MockStreamWaitFn struct {
	mock.Mock
}

type MockStreamWaitFn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamWaitFn) EXPECT() *MockStreamWaitFn_Expecter {
	return &MockStreamWaitFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockStreamWaitFn) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStreamWaitFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStreamWaitFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockStreamWaitFn_Expecter) Execute() *MockStreamWaitFn_Execute_Call {
	return &MockStreamWaitFn_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockStreamWaitFn_Execute_Call) Run(run func()) *MockStreamWaitFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamWaitFn_Execute_Call) Return(_a0 error) *MockStreamWaitFn_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamWaitFn_Execute_Call) RunAndReturn(run func() error) *MockStreamWaitFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStreamWaitFn creates a new instance of MockStreamWaitFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamWaitFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamWaitFn {
	mock := &MockStreamWaitFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
