// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	golm "github.com/a-novel-kit/golm"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/a-novel-kit/golm/utils"
)

// MockChatBase is an autogenerated mock type for the ChatBase type
type MockChatBase struct {
	mock.Mock
}

type MockChatBase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatBase) EXPECT() *MockChatBase_Expecter {
	return &MockChatBase_Expecter{mock: &_m.Mock}
}

// Completion provides a mock function with given fields: ctx, message, options
func (_m *MockChatBase) Completion(ctx context.Context, message golm.UserMessage, options golm.CompletionParams) (*golm.AssistantMessage, error) {
	ret := _m.Called(ctx, message, options)

	if len(ret) == 0 {
		panic("no return value specified for Completion")
	}

	var r0 *golm.AssistantMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, golm.UserMessage, golm.CompletionParams) (*golm.AssistantMessage, error)); ok {
		return rf(ctx, message, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, golm.UserMessage, golm.CompletionParams) *golm.AssistantMessage); ok {
		r0 = rf(ctx, message, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*golm.AssistantMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, golm.UserMessage, golm.CompletionParams) error); ok {
		r1 = rf(ctx, message, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatBase_Completion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Completion'
type MockChatBase_Completion_Call struct {
	*mock.Call
}

// Completion is a helper method to define mock.On call
//   - ctx context.Context
//   - message golm.UserMessage
//   - options golm.CompletionParams
func (_e *MockChatBase_Expecter) Completion(ctx interface{}, message interface{}, options interface{}) *MockChatBase_Completion_Call {
	return &MockChatBase_Completion_Call{Call: _e.mock.On("Completion", ctx, message, options)}
}

func (_c *MockChatBase_Completion_Call) Run(run func(ctx context.Context, message golm.UserMessage, options golm.CompletionParams)) *MockChatBase_Completion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(golm.UserMessage), args[2].(golm.CompletionParams))
	})
	return _c
}

func (_c *MockChatBase_Completion_Call) Return(response *golm.AssistantMessage, err error) *MockChatBase_Completion_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockChatBase_Completion_Call) RunAndReturn(run func(context.Context, golm.UserMessage, golm.CompletionParams) (*golm.AssistantMessage, error)) *MockChatBase_Completion_Call {
	_c.Call.Return(run)
	return _c
}

// CompletionJSON provides a mock function with given fields: ctx, message, options, dest
func (_m *MockChatBase) CompletionJSON(ctx context.Context, message golm.UserMessage, options golm.CompletionParams, dest any) error {
	ret := _m.Called(ctx, message, options, dest)

	if len(ret) == 0 {
		panic("no return value specified for CompletionJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, golm.UserMessage, golm.CompletionParams, any) error); ok {
		r0 = rf(ctx, message, options, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatBase_CompletionJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompletionJSON'
type MockChatBase_CompletionJSON_Call struct {
	*mock.Call
}

// CompletionJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - message golm.UserMessage
//   - options golm.CompletionParams
//   - dest any
func (_e *MockChatBase_Expecter) CompletionJSON(ctx interface{}, message interface{}, options interface{}, dest interface{}) *MockChatBase_CompletionJSON_Call {
	return &MockChatBase_CompletionJSON_Call{Call: _e.mock.On("CompletionJSON", ctx, message, options, dest)}
}

func (_c *MockChatBase_CompletionJSON_Call) Run(run func(ctx context.Context, message golm.UserMessage, options golm.CompletionParams, dest any)) *MockChatBase_CompletionJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(golm.UserMessage), args[2].(golm.CompletionParams), args[3].(any))
	})
	return _c
}

func (_c *MockChatBase_CompletionJSON_Call) Return(err error) *MockChatBase_CompletionJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatBase_CompletionJSON_Call) RunAndReturn(run func(context.Context, golm.UserMessage, golm.CompletionParams, any) error) *MockChatBase_CompletionJSON_Call {
	_c.Call.Return(run)
	return _c
}

// CompletionStream provides a mock function with given fields: ctx, message, options
func (_m *MockChatBase) CompletionStream(ctx context.Context, message golm.UserMessage, options golm.CompletionParams) (<-chan string, utils.StreamWaitFn) {
	ret := _m.Called(ctx, message, options)

	if len(ret) == 0 {
		panic("no return value specified for CompletionStream")
	}

	var r0 <-chan string
	var r1 utils.StreamWaitFn
	if rf, ok := ret.Get(0).(func(context.Context, golm.UserMessage, golm.CompletionParams) (<-chan string, utils.StreamWaitFn)); ok {
		return rf(ctx, message, options)
	}
	if rf, ok := ret.Get(0).(func(context.Context, golm.UserMessage, golm.CompletionParams) <-chan string); ok {
		r0 = rf(ctx, message, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, golm.UserMessage, golm.CompletionParams) utils.StreamWaitFn); ok {
		r1 = rf(ctx, message, options)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(utils.StreamWaitFn)
		}
	}

	return r0, r1
}

// MockChatBase_CompletionStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompletionStream'
type MockChatBase_CompletionStream_Call struct {
	*mock.Call
}

// CompletionStream is a helper method to define mock.On call
//   - ctx context.Context
//   - message golm.UserMessage
//   - options golm.CompletionParams
func (_e *MockChatBase_Expecter) CompletionStream(ctx interface{}, message interface{}, options interface{}) *MockChatBase_CompletionStream_Call {
	return &MockChatBase_CompletionStream_Call{Call: _e.mock.On("CompletionStream", ctx, message, options)}
}

func (_c *MockChatBase_CompletionStream_Call) Run(run func(ctx context.Context, message golm.UserMessage, options golm.CompletionParams)) *MockChatBase_CompletionStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(golm.UserMessage), args[2].(golm.CompletionParams))
	})
	return _c
}

func (_c *MockChatBase_CompletionStream_Call) Return(response <-chan string, wait utils.StreamWaitFn) *MockChatBase_CompletionStream_Call {
	_c.Call.Return(response, wait)
	return _c
}

func (_c *MockChatBase_CompletionStream_Call) RunAndReturn(run func(context.Context, golm.UserMessage, golm.CompletionParams) (<-chan string, utils.StreamWaitFn)) *MockChatBase_CompletionStream_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function with no fields
func (_m *MockChatBase) GetHistory() golm.ChatHistory {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 golm.ChatHistory
	if rf, ok := ret.Get(0).(func() golm.ChatHistory); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(golm.ChatHistory)
	}

	return r0
}

// MockChatBase_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockChatBase_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
func (_e *MockChatBase_Expecter) GetHistory() *MockChatBase_GetHistory_Call {
	return &MockChatBase_GetHistory_Call{Call: _e.mock.On("GetHistory")}
}

func (_c *MockChatBase_GetHistory_Call) Run(run func()) *MockChatBase_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChatBase_GetHistory_Call) Return(_a0 golm.ChatHistory) *MockChatBase_GetHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatBase_GetHistory_Call) RunAndReturn(run func() golm.ChatHistory) *MockChatBase_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// PushHistory provides a mock function with given fields: messages
func (_m *MockChatBase) PushHistory(messages ...golm.MessageWithRole) {
	_va := make([]interface{}, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockChatBase_PushHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushHistory'
type MockChatBase_PushHistory_Call struct {
	*mock.Call
}

// PushHistory is a helper method to define mock.On call
//   - messages ...golm.MessageWithRole
func (_e *MockChatBase_Expecter) PushHistory(messages ...interface{}) *MockChatBase_PushHistory_Call {
	return &MockChatBase_PushHistory_Call{Call: _e.mock.On("PushHistory",
		append([]interface{}{}, messages...)...)}
}

func (_c *MockChatBase_PushHistory_Call) Run(run func(messages ...golm.MessageWithRole)) *MockChatBase_PushHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]golm.MessageWithRole, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(golm.MessageWithRole)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockChatBase_PushHistory_Call) Return() *MockChatBase_PushHistory_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatBase_PushHistory_Call) RunAndReturn(run func(...golm.MessageWithRole)) *MockChatBase_PushHistory_Call {
	_c.Run(run)
	return _c
}

// SetHistory provides a mock function with given fields: history
func (_m *MockChatBase) SetHistory(history golm.ChatHistory) {
	_m.Called(history)
}

// MockChatBase_SetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHistory'
type MockChatBase_SetHistory_Call struct {
	*mock.Call
}

// SetHistory is a helper method to define mock.On call
//   - history golm.ChatHistory
func (_e *MockChatBase_Expecter) SetHistory(history interface{}) *MockChatBase_SetHistory_Call {
	return &MockChatBase_SetHistory_Call{Call: _e.mock.On("SetHistory", history)}
}

func (_c *MockChatBase_SetHistory_Call) Run(run func(history golm.ChatHistory)) *MockChatBase_SetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(golm.ChatHistory))
	})
	return _c
}

func (_c *MockChatBase_SetHistory_Call) Return() *MockChatBase_SetHistory_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatBase_SetHistory_Call) RunAndReturn(run func(golm.ChatHistory)) *MockChatBase_SetHistory_Call {
	_c.Run(run)
	return _c
}

// SetSystem provides a mock function with given fields: system
func (_m *MockChatBase) SetSystem(system *golm.SystemMessage) {
	_m.Called(system)
}

// MockChatBase_SetSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSystem'
type MockChatBase_SetSystem_Call struct {
	*mock.Call
}

// SetSystem is a helper method to define mock.On call
//   - system *golm.SystemMessage
func (_e *MockChatBase_Expecter) SetSystem(system interface{}) *MockChatBase_SetSystem_Call {
	return &MockChatBase_SetSystem_Call{Call: _e.mock.On("SetSystem", system)}
}

func (_c *MockChatBase_SetSystem_Call) Run(run func(system *golm.SystemMessage)) *MockChatBase_SetSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*golm.SystemMessage))
	})
	return _c
}

func (_c *MockChatBase_SetSystem_Call) Return() *MockChatBase_SetSystem_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChatBase_SetSystem_Call) RunAndReturn(run func(*golm.SystemMessage)) *MockChatBase_SetSystem_Call {
	_c.Run(run)
	return _c
}

// NewMockChatBase creates a new instance of MockChatBase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatBase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatBase {
	mock := &MockChatBase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
