// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	models "github.com/a-novel-kit/golm/bindings/groq/models"
	mock "github.com/stretchr/testify/mock"
)

// MockMessage is an autogenerated mock type for the Message type
type MockMessage struct {
	mock.Mock
}

type MockMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessage) EXPECT() *MockMessage_Expecter {
	return &MockMessage_Expecter{mock: &_m.Mock}
}

// Message provides a mock function with no fields
func (_m *MockMessage) Message() models.Message {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 models.Message
	if rf, ok := ret.Get(0).(func() models.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Message)
		}
	}

	return r0
}

// MockMessage_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockMessage_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *MockMessage_Expecter) Message() *MockMessage_Message_Call {
	return &MockMessage_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *MockMessage_Message_Call) Run(run func()) *MockMessage_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_Message_Call) Return(_a0 models.Message) *MockMessage_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessage_Message_Call) RunAndReturn(run func() models.Message) *MockMessage_Message_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessage creates a new instance of MockMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessage {
	mock := &MockMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
